<a href="https://colab.research.google.com/github/ayaaaul/PSDS/blob/main/P4_Deep_Learning_Pre_Processing_dan_Text_Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd from pathlib import Path from urllib.request import urlretrieve folder = Path('data/sms_spam_indonesia') folder.mkdir(parents=True, exist_ok=True) file = folder / 'dataset_sms_spam_v1.csv' if not file.exists(): url = 'https://raw.githubusercontent.com/Andikazidanef15/Sentiment-Analysison-Indonesian-SMS-Dataset/main/dataset_sms_spam_v1.csv' urlretrieve(url, file) d 'normal', 1: 'spam', 2: 'spam'} ) data.head()

In [4]:
import pandas as pd
from pathlib import Path
from urllib.request import urlretrieve

folder = Path('data/sms_spam_indonesia')
folder.mkdir(parents=True, exist_ok=True)
file = folder / 'dataset_sms_spam_v1.csv'

if not file.exists():
    url = 'https://raw.githubusercontent.com/Andikazidanef15/Sentiment-Analysis-on-Indonesian-SMS-Dataset/main/dataset_sms_spam_v1.csv'
    urlretrieve(url, file)

data = pd.read_csv(file).rename(
    columns={'Teks': 'teks', 'label': 'label_asli'}
)
data['label'] = data['label_asli'].map(
    {0: 'normal', 1: 'spam', 2: 'spam'}
)
data.head()

                                                teks  label_asli label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...           2  spam
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...           2  spam
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...           2  spam
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...           2  spam
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...           2  spam

In [9]:
import re

data['huruf_kecil'] = data['teks'].str.lower()
data['bersih'] = data['huruf_kecil'].str.replace(
    r'[^a-z0-9\s]', ' ', regex=True
)
data['bersih'] = data['bersih'].str.replace(
    r'\s+',' ', regex=True
).str.strip()

data[['teks', 'bersih']].head()

,teks,bersih
0,[PROMO] Beli paket Flash mulai 1GB di MY TELKO...,promo beli paket flash mulai 1gb di my telkoms...
1,2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...,2 5 gb 30 hari hanya rp 35 ribu spesial buat a...
2,"2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...",2016 07 08 11 47 11 plg yth sisa kuota flash a...
3,"2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...",2016 08 07 11 29 47 plg yth sisa kuota flash a...
4,4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...,4 5gb 30 hari hanya rp 55 ribu spesial buat an...

In [7]:
import re

def case_folding(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Contoh Penggunaan
teks_awal = "Para mahasiswa sedang mempelajari teknik Preprocessing Data dalam pemrosesan bahasa alami. Mereka sangat antusias!"
hasil_case_folding = case_folding(teks_awal)

print("Hasil Case Folding:")
print(hasil_case_folding)

Hasil Case Folding:
para mahasiswa sedang mempelajari teknik preprocessing data dalam pemrosesan bahasa alami mereka sangat antusias

In [10]:
import nltk
from nltk.tokenize import word_tokenize

# Unduh punkt dan punkt_tab jika belum pernah diunduh
nltk.download('punkt')
nltk.download('punkt_tab')

def tokenisasi(text):
    return word_tokenize(text)

# Contoh Penggunaan (menggunakan hasil dari Case Folding)
input_teks = "para mahasiswa sedang mempelajari teknik preprocessing data dalam pemrosesan bahasa alami mereka sangat antusias"
hasil_tokenisasi = tokenisasi(input_teks)

print("Hasil Tokenisasi:")
print(hasil_tokenisasi)

Hasil Tokenisasi:
['para', 'mahasiswa', 'sedang', 'mempelajari', 'teknik', 'preprocessing', 'data', 'dalam', 'pemrosesan', 'bahasa', 'alami', 'mereka', 'sangat', 'antusias']

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [12]:
!pip install Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

def stopword_removal(tokens):
    factory = StopWordRemoverFactory()
    stopword = factory.create_stop_word_remover()

    # Memfilter list token
    filtered_tokens = [word for word in tokens if stopword.remove(word) != '']
    return filtered_tokens

# Contoh Penggunaan (menggunakan hasil dari Tokenisasi)
input_tokens = ['para', 'mahasiswa', 'sedang', 'mempelajari', 'teknik', 'preprocessing', 'data', 'dalam', 'pemrosesan', 'bahasa', 'alami', 'mereka', 'sangat', 'antusias']
hasil_stopword = stopword_removal(input_tokens)

print("Hasil Stopword Removal:")
print(hasil_stopword)

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1
Hasil Stopword Removal:
['mahasiswa', 'sedang', 'mempelajari', 'teknik', 'preprocessing', 'data', 'pemrosesan', 'bahasa', 'alami', 'sangat', 'antusias']

In [13]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def stemming(tokens):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()

    # Mengubah setiap token ke kata dasar
    stemmed_tokens = [stemmer.stem(word) for word in tokens]
    return stemmed_tokens

# Contoh Penggunaan (menggunakan hasil dari Stopword Removal)
input_tokens = ['mahasiswa', 'mempelajari', 'teknik', 'preprocessing', 'data', 'pemrosesan', 'bahasa', 'alami', 'antusias']
hasil_stemming = stemming(input_tokens)

print("Hasil Stemming:")
print(hasil_stemming)

Hasil Stemming:
['mahasiswa', 'ajar', 'teknik', 'preprocessing', 'data', 'pemrosesan', 'bahasa', 'alami', 'antusias']